# Generated by Django 5.0.7 on 2024-07-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateapplications',
            old_name='yearOfExperience',
            new_name='yearOfExp',
        ),
    ]
