# Generated by Django 5.0.7 on 2024-07-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_yearofexperience_candidateapplications_yearofexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplications',
            name='cgpa',
            field=models.IntegerField(default=0),
        ),
    ]
