# Generated by Django 5.0.7 on 2024-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_candidateapplications_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='companyDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='companyLogoUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
