# Generated by Django 5.0.7 on 2024-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_jobpost_companydescription_jobpost_companylogourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='passingYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Pending', max_length=50),
        ),
    ]
