# Generated by Django 5.0.7 on 2024-07-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_myapplyjoblist_user'),
        ('hr', '0002_rename_yearofexperience_candidateapplications_yearofexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplications'),
        ),
    ]
